### ISSUE TITLE
Blank page after using root file

### ISSUE THREAD

**Issue by mengcaopsy** [memphis-iis/mofacts-ies#1188]
There is nothing coming up after using the root file to select from 6 conditions.
![image](https://github.com/memphis-iis/mofacts-ies/assets/43429451/6da6c870-1dfe-4698-a965-9739fafa0a17)

**Comment by imrryr** [comment]
Please check on how "randomizedDelivery": "1" is used in the code... I looked and couldn't really tell, but I think it specifies the lockout minutes possibilities, but that begs the question of why it is needed at all since the number of possibilities also may specify this if there is no root file I thought....

**Comment by mengcaopsy** [comment]
@MegaGeese [Chinese radicals final version.zip](https://github.com/memphis-iis/mofacts-ies/files/12017739/Chinese.radicals.final.version.zip)
Here it is.

**Comment by MegaGeese** [comment]
Yeah there was a bug in the file uploader as well which was breaking package upload with subtdfs

**Comment by mengcaopsy** [comment]
@JRustyHaner @MegaGeese I tested it just now and the problem is still there. When shall I test again? I am not sure how long does it take for you to update the code,
