### ISSUE TITLE
A bug in the Outcome column of the data file

### ISSUE THREAD

**Issue by mengcaopsy** [memphis-iis/mofacts-ies#1198]
There is an error in the data file that it marked correct for the timeout reactions.
![image](https://github.com/memphis-iis/mofacts-ies/assets/43429451/3c789dd1-a99e-4a3a-8b12-4bc8086b4a6d)

**Comment by JRustyHaner** [comment]
@mengcaopsy could you please let us know which TDF this output is for?

**Comment by MegaGeese** [comment]
looks like these are study trials that are being counted as 'correct' but since there is no way for the user to answer it is also recorded as a timeout. I can add a new parameter in how its recorded so that instead of [timeout] it will say something like [study]
Should study trials still be counted as correct?

**Comment by imrryr** [comment]
Ok, let's mark those as study for the outcome, the response itself should
be blank. There is no response. There is also no feedback. Is anything else
ambiguous at first glance?
