### ISSUE TITLE
side by side display for image mc button questions

### ISSUE THREAD

**Issue by imrryr** [memphis-iis/mofacts-ies#1295]

**Comment by imrryr** [comment]
See #1213 which explains this recurring issue. Meng, please elaborate on any other display issue here.

**Comment by imrryr** [comment]
OK, the details for uiSettings needed are
- make the feedback allowable on a single-line
- allow feedback to appear on the bottom instead of the top
- allow the button test screen to be organized left/picture and right/ buttons like #1213 
- remove the list of answers from the button incorrect and correct feedback screen, showing only the feedback line and stimulus (no longer on the left, but centered since the buttons are gone). If the buttons are present, we need to make the correct answer show on the buttons (highlight the correct answer button somehow) 
- hide "your answer: X" on the correct feedback screen (the correct feedback screen is also not intended to re show stimuli, but the existing stimuli can be retained. The correct feedback portion can simply add the word "Correct." to the Test screens, Currently the way it replaces the student response with the stimuli is OK, but not needed. The student isn't actually studying during correctness feedback.

Should I create additional issues @JRustyHaner? Do you see any hangups that suggest we need to use the old version for times sake also Rusty? Or simply any adjustments to my ideas?

**Comment by imrryr** [comment]
@JRustyHaner Maybe this is the last of the details for a while, its already looking OK, we just want it to look great:

- The word "Correct" or "Incorrect" is not colored (this is a bug)
- There needs to be a at least 1 blank line between the score and feedback (when feedback is on the top) (this can be general, not a ui setting)
- This score needs to be much less prominent, let's make it gray and right justify it to the top right, and make it much smaller. As far as I am concerned it was always too distracting and these changes can be general, (not a ui setting)

**Comment by JRustyHaner** [comment]
@imrryr looking at this this morning

**Comment by JRustyHaner** [comment]
Also changing displayUserAnswerAtTop to displayUserAnswerInFeedback for clarity

**Comment by mengcaopsy** [comment]
I was testing the bird experiment after adding the UI setting code. During the learning session, after I clicked a button, it switched to a feedback page with no options displaying on the screen. 
The first problem is that if my previous trial is correct, the feedback "You answer: undefined correct" will stay on the screen for the current trial until I make a selection. 
The second problem with the feedback is that it says "Your answer: undefined incorrect. The correct answer is Jay." I'm not sure what the word "undefined" means. Since we don't have to show participants' responses, can we just keep the word "Correct/Incorrect. The correct answer is __"?

"uiSettings": {
          "displayReviewTimeoutAsBarOrText": "false",
          "displayReadyPromptTimeoutAsBarOrText": "false",
          "displayCardTimeoutAsBarOrText": false,
          "displayTimeOutDuringStudy": false,
           "singleLineFeedback" :true,
           "feedbackDisplayPosition" :"bottom",
          "stimuliPosition" :"left"
         },

![image](https://github.com/memphis-iis/mofacts-ies/assets/43429451/4860a8fc-dcc2-4181-9a64-63dc79b62c04)
![image](https://github.com/memphis-iis/mofacts-ies/assets/43429451/41d513cc-cce4-45d6-8d28-d26ad5565e3c)


What I think is good is below. If we can't do this, at least remove the additional words I mentioned above.
![image](https://github.com/memphis-iis/mofacts-ies/assets/43429451/9bb52722-00df-4e12-915f-7fd7ba2e5fd3)

A minor point is whether we can make the background of the options to be squared. This isn't that important. I am more used to the squared ones.
![image](https://github.com/memphis-iis/mofacts-ies/assets/43429451/eea086ca-cbeb-4162-9f68-ed8340ec681a)
