### ISSUE TITLE
The data download issue on staging

### ISSUE THREAD

**Issue by mengcaopsy** [memphis-iis/mofacts-ies#1297]
I was trying to download the data I tested. The download all tdf link does not work and each tdf data file is empty.
![image](https://github.com/memphis-iis/mofacts-ies/assets/43429451/43cda28f-6810-4f41-8357-81457f89dfe7)
![image](https://github.com/memphis-iis/mofacts-ies/assets/43429451/aae875f0-d327-42a0-b801-922eba3199e3)

**Comment by imrryr** [comment]
[birdlowsim1-data.txt](https://github.com/memphis-iis/mofacts-ies/files/13183326/birdlowsim1-data.txt)
[birdhighsim1-data.txt](https://github.com/memphis-iis/mofacts-ies/files/13183327/birdhighsim1-data.txt)
That's funny, I get the individual files when I try. So that part is an access error for a teacher account. (Meng, can you make a screenshot of console for when you try)

But I get this when I press the all button, so the all button is really broken totally it seems
![mofacts_app - Google Chrome 10_26_2023 5_22_27 PM](https://github.com/memphis-iis/mofacts-ies/assets/13023147/e56ad24a-772d-4d9a-b06a-d5f8ab1c814d)

**Comment by mengcaopsy** [comment]
Sure. Here it is.

![image](https://github.com/memphis-iis/mofacts-ies/assets/43429451/1ebd79d9-07e3-4397-898c-6f129023a325)
![image](https://github.com/memphis-iis/mofacts-ies/assets/43429451/b2e8a461-d121-45bf-87f4-34d5aed9739a)
