### ISSUE TITLE
All function in teacher progress reports

### ISSUE THREAD

**Issue by imrryr** [memphis-iis/mofacts-ies#163]
It was broken when I worked with Roy. Needs to be fixed ASAP. Also, the dropdown lists a number of tdfs not assigned to the course selected. This is a bug also. It should only show tdfs assigned for the class selected.

**Comment by imrryr** [comment]
Tell me if I need to split this into 2 issues

**Comment by imrryr** [comment]
Another aspect of this is that when All is selected it should be All for the tdf that is selected, NOT All for the user in all classes

**Comment by andrewtackett** [comment]
Fixed with commits 325dc35a52a9bc92c0a2af85de8daafcc5a9be07 and d19e16548ae31ad2d0750789c2a778cbb92e2141 respectively.

"Another aspect of this is that when All is selected it should be All for the tdf that is selected, NOT All for the user in all classes"

I think this was referring to how we calculate the reports.  Right now we do only learning session items in the selected tdf (which could be all in the current class).  I think I told you differently before and I was mistaken.  Please reopen and explain if this isn't what this comment referred to.

**Comment by imrryr** [comment]
All was giving practice for classes in the last semester when I checked it with Roy. When ALL tdfs for the selected class, not all tdfs for All classes

**Comment by andrewtackett** [comment]
"was giving practice"

What does this mean?  "It counted practice from a previous semester in the current semester totals" appears to be what you're trying to refer to but you're also bringing up what appears to be an unrelated item which is what tdfs are in the dropdown (which I just fixed).

**Comment by imrryr** [comment]
"giving practice" = supplying student time and percentage results for

**Comment by imrryr** [comment]
this is also why I asked early on if this should be split into 2 issues...

**Comment by andrewtackett** [comment]
Alright I think I see.  You were referring to what happens when the all options is selected for the tdf, not what tdf options exist in the dropdown.  I would say the main concept of this issue being incorrect all functionality fits with this portion.  I would've split off the dropdown options needing to be different to a different issue for future reference (it's fine in this issue).

I'm pretty sure you must have looked with Roy on your login.  The code now and from when this issue was created both query by the current class AND semester, UNLESS you're logged in as an admin.  I don't see how else they could have possibly had incorrect results in that context when we do wholly new classes and tdfs each semester (the basic database query would have filtered out what you're saying).  Were you looking on your login?  Also what specifically made Roy/you sure it was from last semester?

**Comment by imrryr** [comment]
It was on Roy's login, the student was in classes in both Spring and Fall. We totaled the practice in his classes and it didn't show what All showed for this student I recall.

**Comment by andrewtackett** [comment]
Fixed with commit: 7baf65f835a20c6be797135907255d7f45be79d1

This commit makes sure to only show instructors classes, tdfs, and data from the current semester/class.  It also makes sure students logging in through the signinsouthwest page see only data from the class they sign in from (which should be limited to only classes from the current semester).  Also I made it so when drilling down to an individual student record from instructor reporting the same tdf is selected.  Finally there are some bug fixes as well.
