### ISSUE TITLE
Meng's learning session won't work

### ISSUE THREAD

**Issue by imrryr** [memphis-iis/mofacts-ies#174]
It errors in console with "loading...." on the screen for first trial. Meng is sending more info.

Based on the error referencing hintsyls, I think the hintsyls is trying to provide hints for Meng's tones. We need a way to have hint syls only fire if stimuli is cloze. Also, hintsyls code should not activate unless there is a tag in the tdf, to prevent time wasted calling the code when it is not needed.

**Comment by andrewtackett** [comment]
Fixed with commit: acf5aa1d6dd5303af0c02ec7dd4122de833c39bc

@imrryr "Also, hintsyls code should not activate unless there is a tag in the tdf" it currently activates if hintsylls is present in the calculateProbability formula for the current unit.  Please open a new issue if you want to refine this more/change it (as it wasn't the problem here).
