### ISSUE TITLE
Feedback for button trials with images should also be images

### ISSUE THREAD

**Issue by imrryr** [memphis-iis/mofacts-ies#176]
Currently, it presents the filename as feedback text

**Comment by andrewtackett** [comment]
@wscarter This might be as simple as {{{feedbackText}}} instead of {{feedbackText}}

**Comment by andrewtackett** [comment]
Implemented with commit: a3e12c9940dcc967c03917bde5c6d5840d56379e

@imrryr I put some feedback text in to contextualize displaying the correct image.  It is currently "Incorrect.  The correct response is displayed below."  Please let me know if there's a better line for this.

I've defaulted the image display size since the exact combination isn't easy to tell from all the css on the buttons.  I'll be asking Wei via email what size they've created images as to fit the buttons to get a better idea of good dimensions for this so the response is displayed the same as the button images.

**Comment by andrewtackett** [comment]
CSS should be almost identically duplicated via commit: b555727223e23ec2f23b8911787de183ac95f80a

Closing for now.
