### ISSUE TITLE
Need time filter for instructor/ student progress reports

### ISSUE THREAD

**Issue by imrryr** [memphis-iis/mofacts-ies#193]
The need is so that teachers can determine how much is done by a due date. Should be a control like this beneath the class and tdf selections

"Report practice before [time/date selector widget of some sort]"
Widget defaults to current time

**Comment by wscarter** [comment]
This isn't possible to do with instructor reporting in its current state because we rely on user metrics in MongoDB to get overall progress reports.  The user metrics items contain an accumulated count of the number of times a given question has been answered, making it impossible to determine the date on which it was answered.  It is possible to replay the entire user logs (where we do have dates) to recalculate these values, but that would require considerable effort outside the scope of this issue, and it would be exceedingly slow to load.  After discussing with @andrewtackett, this would be a lot cleaner to revisit after we've begun migrating to a relational database.  What are your thoughts @imrryr ?

**Comment by imrryr** [comment]
@wscarter well I'm wondering how we produce the downloadable data then? Do we replay all the subjects? What I want is inferable from the data downloads...

**Comment by wscarter** [comment]
The data downloads are (mostly) just reads from the database and are already quite slow and CPU intensive.

**Comment by andrewtackett** [comment]
Consider how unbearably slow drilling down to one student page is from
instructor reporting.  Then multiply that by N students per teacher at
least any time the instructor reporting page is brought up.

IIRC we did replay logs for instructor reporting originally and it was so
slow we immediately took down reporting to swap over to something faster.

On Thursday, September 10, 2020, wes <notifications@github.com> wrote:
> The data downloads are (mostly) just reads from the database and are
already quite slow and CPU intensive.
>
> —
> You are receiving this because you were mentioned.
> Reply to this email directly, view it on GitHub, or unsubscribe.<
https://ci4.googleusercontent.com/proxy/PHi9O3mR3zh5tkH-eeMKbOuQlRQER12Ep4wyNwpwZJOZaF8KPLryP4feZbG7YExsj4W9XvoZJuctS0bc--hcTMlWKIlbr_KQ5F1uWB-mJ87E0qHLnpwsazXKkxS7VZbkRYXL9JW69dKhjAQnyY6-45EeAtslHdXbltEmrkKyXErKMcnrxHRJt1lHaCDhIOCJCTCrlw_qJp--hbdu0aeoTPVj_HKEY3oUOOpwnodq9A=s0-d-e1-ft#https://github.com/notifications/beacon/ABIWVHE4QOTBK3NRKD4OHOTSFFDSPA5CNFSM4QQYLP6KYY3PNVWWK3TUL52HS4DFVREXG43VMVBW63LNMVXHJKTDN5WW2ZLOORPWSZGOFEWA55I.gif>

**Comment by andrewtackett** [comment]
Done in postgres branch
