### ISSUE TITLE
TTS and SR in Dialogue

### ISSUE THREAD

**Issue by imrryr** [memphis-iis/mofacts-ies#196]
Enhancement to make this work

**Comment by andrewtackett** [comment]
This issue is to make sure that text to speech and speech to text work with the new dialogue loop

@wscarter Take a look at the audio processing loop.  Should be able to detect which input box is currently on screen and branch similar to existing logic.  The new dialogue loop has a new template where transcription results should be put and allowed.  TTS should be easy, just need to trigger it during the dialogue loop.

**Comment by andrewtackett** [comment]
Completed with commits: 669e138961a0ebb25c914d731d469c751b425ef9, 74b041ae2a2b2e3e214e345c8017ccec6c636671, 0c14757d419c4e8b1a12e3ff0e5ccf29ac381a3b
