### ISSUE TITLE
New predictor for model

### ISSUE THREAD

**Issue by imrryr** [memphis-iis/mofacts-ies#29]
I found a better model that needs to uses the not created variable p.responseSecsSinceLastShown which is exactly like the one for stims, but now for each response. Next week is fine.

**Comment by andrewtackett** [comment]
Added with commit: 84e832f4206f49f152090f629fa5558a60f0cd07

Note: the secs since last shown defaults to fractionally above 0 (the time it takes to simulate going back through all the user time logs) if the user has navigated away from mofacts and come back later to the same practice.  This is true of stimSecsSinceLastShown and questionSecsSinceLastShown as well due to them not being saved in the database.  Not sure if this is the desired functionality or not.

If not, please open up a new issue and refer to this comment and I'll work on fixing it.

Also please reopen if this feature doesn't work as intended.
