### ISSUE TITLE
Perception/Efficacy of science scale added to document for survey stim file

### ISSUE THREAD

**Issue by kaitlynpeperone** [memphis-iis/mofacts-ies#44]

**Comment by aolney** [comment]
Could you copy/paste the link to the file(s) as a comment?

**Comment by kaitlynpeperone** [comment]
https://docs.google.com/document/d/1EDAWvMrYMP_upvYcEpQgfz6OfQbZGmyzWFsI2vIKmpc/edit

**Comment by aolney** [comment]
OK it looks like you want me to give you scales to include. Here is my analysis, previously on another google sheet. See recommendations at the end.

## Overview

1. Here is a study of motivation measures for A&P
https://www.physiology.org/doi/pdf/10.1152/advan.00091.2015
Interestingly, they find that intrinsic motivation has no predictive value and that two extrinsic scales mattered:
EM introjected is when one engages in a behavior to maintain personal expectations or avoid guilt. EM external is when an individual participates in an activity solely

2. Here is a recent annotated bibliography by IES of self-efficacy type instruments:
https://ies.ed.gov/ncee/edlabs/regions/appalachia/askarel/pdf/08_AAR_508.pdf

3. One of the items it references has a nice 10 item scale, but it overlaps a lot with MSLQ, so I’m not sure you’d use it in addition to MSLQ:
https://www.researchgate.net/publication/266394678_A_Practical_Measure_of_Student_Motivation_Establishing_Validity_Evidence_for_the_Expectancy-Value-Cost_Scale_in_Middle_School

4. One of the items it references is an IES report comparing 21 instruments, including the MSLQ: https://files.eric.ed.gov/fulltext/ED514996.pdf

5. One of the 21 that might be interesting for additional items is the Student Engagement Instrument (SEI; p46). It has subscales for future aspirations and extrinsic motivation; however, some items need to be rewritten for college use 
(http://www.psychwiki.com/dms/other/labgroup/Measufsdfsdbger345resWeek1/Krisztina/Appelton2006.pdf)

## Recommendations

Use the A&P measures of extrinsic motivation. Example item adaptations for HS and medical school:
- https://www.lrcs.uqam.ca/wp-content/uploads/2017/08/HS-emes_en.pdf
- https://bmcmededuc.biomedcentral.com/articles/10.1186/s12909-017-0856-9/tables/1

**The first link has a key for the 8 items previously found to be predictive of achievement. These are the only items I would recommend adding.**

Otherwise use the MLSQ items we already have.

*If we want to rethink the whole approach and/or condense it, review the IES report on measures and possibly use the 10 item scale.*
