### ISSUE TITLE
Data detail

### ISSUE THREAD

**Issue by imrryr** [memphis-iis/mofacts-ies#619]
I think this request is pretty small, so hopefully it can be added to the stack (I realize it is a new feature, so if it is not really small, due to writing a complicated query), please just verify this info is in the database, and we can add it to the output later. So the request is to create 2 new columns, inserted between the 4th and 5th columns, Condition Name will equal "section" always for datashop compatibility, and Condition type will equal the concatenation of the teachers email and the section.

Headers
Condition Name	Condition Type

**Comment by imrryr** [comment]
issue #474 is the data we are talking about here

**Comment by JRustyHaner** [comment]
@imrryr inserting it before row 5 would break all current data. I could insert it there.

**Comment by imrryr** [comment]
why would it break anything, the report is a new query each time right? So it is always all the data...

**Comment by JRustyHaner** [comment]
Because the database sets unique column indexes to each column
{column A, column B} has Ids of {1,2}. If I add column C between A and B to where its {column A, column B, column C} the unique ids would still be {1, 2, 3} and all data would shift left one cell. 

Andrew didn't write any way to reorder the data in there, and if I add a column it would be to the end of the set.

**Comment by imrryr** [comment]
I still don't understand, why would the data report be associated with the database. The data report should be merely a query on the database, no?

**Comment by imrryr** [comment]
But anyhow, I believe you even if I don't understand, putting at the end is fine for now, I just want it to better analyze and compare the data report with the teacher reports and progress reports
