### ISSUE TITLE
Not reporting the review time

### ISSUE THREAD

**Issue by imrryr** [memphis-iis/mofacts-ies#624]
**Describe the bug**
CF (Review Latency) in the data output is a single digit integer when it should be the milliseconds in review whether that review is simple, refutational or dialogue

**Comment by imrryr** [comment]
Is this a database or reporting issue?

**Comment by JRustyHaner** [comment]
@imrryr it's being recorded in the database as integer
![image](https://user-images.githubusercontent.com/46696077/153650578-de4fae98-5bca-463e-9377-34f9f1488acc.png)

**Comment by imrryr** [comment]
OK, so well figure out why that is, maybe the timer is just dividing by 1000 and rounding.... We want to track it with the same metric as the start and end latency.... This may mean the times of the practice were wrong, or they will need to be fixed if the were correct, since the input to compute the time will change.

**Comment by imrryr** [comment]
Anyhow, it can't be seconds, since 3 and 4 are not valid review times in seconds.... so perhaps it is just the time is saving this data before the review completes or something strange like that

**Comment by JRustyHaner** [comment]
@imjeffhi4 it's reporting that way, for some odd reason. The numbers are sound so far.

**Comment by JRustyHaner** [comment]
@imrryr the math is correct

![image](https://user-images.githubusercontent.com/46696077/153662250-6d567afa-60b3-4d0e-b3e1-e0f5992d4671.png)

**Comment by imrryr** [comment]
OK, so when the record is taken is wrong?

**Comment by JRustyHaner** [comment]
@imrryr Date.now()

**Comment by JRustyHaner** [comment]
@imrryr No, date.now() is the only function being called on any of these variables, which means that the placement of them is wrong. 
userFeedbackStart is set at the beginning of showUserFeedback (line 1378 card.js) using Date.now()
reviewBegin is set  after the answer feedback callback is called (line 1488 card.js) using Date.now()
reviewEnd is set after a few lines later (line 1501) using Date.now()
 
That means that the difference between reviewEnd and reviewBegin is going to be negligible, since the code between them is not complicated at all. Same with userFeedbackStart and reviewEnd. There's nothing preventing the code from zipping along between them, no user input or countdown timers.

**Comment by imrryr** [comment]
So it is just being called in the wrong place

**Comment by JRustyHaner** [comment]
That's likely. Where should it be called?

**Comment by imrryr** [comment]
Really good we got this one

**Comment by imrryr** [comment]
It just measures the time of the review, so it should initiate as soon as the countdown timer starts that is displayed for the student when the review is displayed. It ends when the review disappears for the next trial...
