### ISSUE TITLE
Add check on pages where user shouldn't be logged in

### ISSUE THREAD

**Issue by imrryr** [memphis-iis/mofacts-ies#649]
**Describe the bug**
If you are on the course selection screen, after choosing the teacher, hitting back produces this. Can we do something less confusing then this, assuming it is difficult to just make the back button function normally

**Comment by imrryr** [comment]
This is what you get after hitting back...

![mofacts_app and 4 more pages - Personal - Microsoft​ Edge 2_16_2022 8_05_17 AM](https://user-images.githubusercontent.com/13023147/154281156-6029f700-77b7-40d0-85ac-14d4ee7f5fd4.png)

**Comment by JRustyHaner** [comment]
@imrryr this was the fix for an earlier problem, where hitting the back button during a trial would push you to a blank instructions page.  We could redirect the back button to...
-Logout and Go to Home
-If logged in, go to profile and fix the tdf menu (that's a seperate issue), if logged out, go to home page before login

I'd lean on two.

**Comment by imrryr** [comment]
You understand I was NOT logged in here, so it shouldn't go to the profile page? Your response suggest perhaps you didn't understand I was no the class selection, not chapter selection when I hit back. So I was not logged in

**Comment by JRustyHaner** [comment]
@imrryr aah, yeah I can see where that would happen. I'll fix it.
