### ISSUE TITLE
History not reporting correct time

### ISSUE THREAD

**Issue by MegaGeese** [memphis-iis/mofacts-ies#672]
Currently feedback duration nor dialogue duration is not recorded. 

We can put them both into the same column in the database or I can make a separate column for each. It should be noted that the user shouldn't have both feedback and dialogue at the same time for a single trial. 

response time is also recording the server time when the user submits an answer instead of the time it took for the user to finish typing the answer. Is this correct?

**Comment by imrryr** [comment]
Sorry I have a meeting in 3 minutes. So feedback duration didn't get fixed when the issue was closed? They are supposed to be in the same column... never indicated differently. 

There are 3 columns, 1 is when they start typing, one is when they hit return, and 1 is all the feedback (regardless of which type) together they need to let you infer the total time the student practices.

Its really pretty logical and should make perfect sense unless I am being unclear.

**Comment by MegaGeese** [comment]
I thought that was the case and just wanted to be sure. Thanks
