### ISSUE TITLE
Better support for due dates in tdfs (backend)

### ISSUE THREAD

**Issue by imrryr** [memphis-iis/mofacts-ies#840]
a due date is a new value in the set spec, it is used by the progress report to split the time spent into two values (amount after due date and amount before). This occurs for both the student and teacher reports. Both teacher and student reports will then report the time split into before and after the due date. As an extension of this enhancement, teachers requested the ability to declare exemptions for a student, which would allow them to manually assign the due date for a tdf for a student. This function is tricky, since how will we handle this so that students who have not logged in can be granted exemptions. Perhaps we will just require that the student to have logged in once before exceptions can be created. However, there may not be any practice for the Chapter until after the extension is granted, so we might need some log table for each tdf that tracks extensions (alternatives to the tdf for particular users...

**Comment by JRustyHaner** [comment]
@imrryr thinking about this, as far as the per student exceptions.

We can create a log table, but currently since postgres still is the main storage mechanism for tdfs and we are removing postgres in the future, I'd shy away from adding anything to the tdf table in postgres. A fix for that is to create a new mongo collection that has the exceptions table that closely matches the current tdf table in postgres and then merge it later into the main tdf collection  after the postgres regression.

@MegaGeese  what do you think?
